# automatically generated by ./configure on Fri Jan 19 21:06:15 CST 2018

### configuration options ###

# authentification method (pam or shadow)
AUTH_METHOD = pam
# also prompt for the root password in adition to the user's
ENABLE_ROOT_PASSWORD = yes
# enable plugins for vlock-main
ENABLE_PLUGINS = yes
# which plugins should be build
MODULES = all.so new.so nosysrq.so train.so
# which scripts should be installed
SCRIPTS = 

# root's group
ROOT_GROUP = root

# group for privileged plugins
VLOCK_GROUP = vlock
# mode for privileged plugins
VLOCK_MODULE_MODE = 0750

### paths ###

# installation prefix
PREFIX = /usr/local
BINDIR = $(PREFIX)/bin
SBINDIR = $(PREFIX)/sbin
LIBDIR = $(PREFIX)/lib
MANDIR = $(PREFIX)/share/man
# installation root
DESTDIR =
# path where modules will be located
MODULEDIR = $(LIBDIR)/vlock/modules
# path where scripts will be located
SCRIPTDIR = $(LIBDIR)/vlock/scripts

### programs ###

# shell to run vlock.sh with (only bash is known to work)
BOURNE_SHELL = /bin/sh
# C compiler
CC = gcc
# linker
LD = ld
# mkdir
MKDIR_P = mkdir -p
# install
INSTALL = install

### compiler and linker settings ###

# C compiler flags
CFLAGS = -O2 -Wall -W -pedantic -std=gnu99 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
# libraries
LDLIBS = -lgobject-2.0 -lglib-2.0
# linker flags
LDFLAGS = 
# linker flags needed for dlopen and friends
DL_LIB = -ldl
# linker flags needed for crypt
CRYPT_LIB = -lcrypt
# linker flags needed for pam
PAM_LIBS = -ldl -lpam
